# Travel Assistant Environment Setup Script
# This script helps you configure your environment variables for Docker

Write-Host "🚀 Travel Assistant Environment Setup" -ForegroundColor Green
Write-Host "=====================================" -ForegroundColor Green

# Check if .env file exists
if (Test-Path ".env") {
    Write-Host "✅ .env file already exists" -ForegroundColor Yellow
    $overwrite = Read-Host "Do you want to overwrite it? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "Setup cancelled." -ForegroundColor Red
        exit
    }
}

Write-Host "`n📝 Please provide your API keys:" -ForegroundColor Cyan

# Get ChatGPT API key
$chatgptKey = Read-Host "Enter your ChatGPT API key (or press Enter to skip)"
if ([string]::IsNullOrWhiteSpace($chatgptKey)) {
    $chatgptKey = "your_chatgpt_api_key_here"
}

# Get Google Maps API key
$googleMapsKey = Read-Host "Enter your Google Maps API key (or press Enter to skip)"
if ([string]::IsNullOrWhiteSpace($googleMapsKey)) {
    $googleMapsKey = "your_google_maps_api_key_here"
}

# Generate a random secret key
$secretKey = -join ((1..32) | ForEach {[char]((65..90) + (97..122) + (48..57) | Get-Random)})

# Create .env file
$envContent = @"
# Travel Assistant Environment Variables
# Generated by setup script on $(Get-Date)

# API Keys
VITE_CHATGPT_API_KEY=$chatgptKey
VITE_GOOGLE_MAPS_API_KEY=$googleMapsKey

# Environment
VITE_NODE_ENV=production

# Database Configuration (for auth backend)
DATABASE_URL=postgresql+asyncpg://travel_user:travel_password@db:5432/travel_assistant_auth
SECRET_KEY=$secretKey
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=15
REFRESH_TOKEN_EXPIRE_DAYS=7
API_PREFIX=/api/v1
ENV=production
LOG_LEVEL=INFO
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost

# PostgreSQL Database
POSTGRES_DB=travel_assistant_auth
POSTGRES_USER=travel_user
POSTGRES_PASSWORD=travel_password
"@

$envContent | Out-File -FilePath ".env" -Encoding UTF8

Write-Host "`n✅ Environment configuration saved to .env file" -ForegroundColor Green

# Show next steps
Write-Host "`n🚀 Next Steps:" -ForegroundColor Cyan
Write-Host "1. Start the application:" -ForegroundColor White
Write-Host "   docker compose up --build" -ForegroundColor Yellow
Write-Host "`n2. Or for development:" -ForegroundColor White
Write-Host "   docker compose -f docker-compose.dev.yml up --build" -ForegroundColor Yellow
Write-Host "`n3. Access the application:" -ForegroundColor White
Write-Host "   Frontend: http://localhost:3000" -ForegroundColor Yellow
Write-Host "   Backend API: http://localhost:8001" -ForegroundColor Yellow
Write-Host "   API Docs: http://localhost:8001/docs" -ForegroundColor Yellow

Write-Host "`n📚 For more information, check the README.md file" -ForegroundColor Cyan

