#!/bin/bash

# Travel Assistant Environment Setup Script
# This script helps you configure your environment variables for Docker

echo "🚀 Travel Assistant Environment Setup"
echo "====================================="

# Check if .env file exists
if [ -f ".env" ]; then
    echo "✅ .env file already exists"
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! $overwrite =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

echo ""
echo "📝 Please provide your API keys:"

# Get ChatGPT API key
read -p "Enter your ChatGPT API key (or press Enter to skip): " chatgpt_key
if [ -z "$chatgpt_key" ]; then
    chatgpt_key="your_chatgpt_api_key_here"
fi

# Get Google Maps API key
read -p "Enter your Google Maps API key (or press Enter to skip): " google_maps_key
if [ -z "$google_maps_key" ]; then
    google_maps_key="your_google_maps_api_key_here"
fi

# Generate a random secret key
secret_key=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)

# Create .env file
cat > .env << EOF
# Travel Assistant Environment Variables
# Generated by setup script on $(date)

# API Keys
VITE_CHATGPT_API_KEY=$chatgpt_key
VITE_GOOGLE_MAPS_API_KEY=$google_maps_key

# Environment
VITE_NODE_ENV=production

# Database Configuration (for auth backend)
DATABASE_URL=postgresql+asyncpg://travel_user:travel_password@db:5432/travel_assistant_auth
SECRET_KEY=$secret_key
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=15
REFRESH_TOKEN_EXPIRE_DAYS=7
API_PREFIX=/api/v1
ENV=production
LOG_LEVEL=INFO
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost

# PostgreSQL Database
POSTGRES_DB=travel_assistant_auth
POSTGRES_USER=travel_user
POSTGRES_PASSWORD=travel_password
EOF

echo ""
echo "✅ Environment configuration saved to .env file"

# Show next steps
echo ""
echo "🚀 Next Steps:"
echo "1. Start the application:"
echo "   docker compose up --build"
echo ""
echo "2. Or for development:"
echo "   docker compose -f docker-compose.dev.yml up --build"
echo ""
echo "3. Access the application:"
echo "   Frontend: http://localhost:3000"
echo "   Backend API: http://localhost:8001"
echo "   API Docs: http://localhost:8001/docs"

echo ""
echo "📚 For more information, check the README.md file"

